version: "2"
services:
  app:
    build:
      context: .
    command: "bash -c 'bundle && bundle exec ruby generate.rb > functions/emoji.fish && chmod 755 functions/emoji.fish'"
    volumes:
      - .:/emoji.fish
      - bundle-data:/usr/local/bundle/
volumes:
  bundle-data:
    driver: local
